### ISSUE TITLE
import ngt ok but import ngtpy show  No module named 'ngtpy

### ISSUE THREAD

**Issue by Ashl1873** [yahoojapan/NGT#129]
pip3 install ngt and it happend 
python=3.8 
pip3 list
show ngt = 1.12.2

**Comment by Ashl1873** [comment]
read code.
and can use this 
from ngt import base as ngt 
ngt.Index.create(...)

**Comment by masajiro** [comment]
There are two types of NGT python packages:  ngtpy and ngt, but ngt is now not maintained.

Since you can use the ngt python package, I think that you have already built and install NGT from the source code. When you use ngtpy that is installed with pip from pypi, you don't need to install NGT from the source code. The installed NGT from the source code might cause this issue.

**Comment by Ashl1873** [comment]
it's not, I can't installed NGT from source code. because my mac os version, probably. make it, show error. And I just use pip3 install it.

And of course, show ngtpy No module balabala.

However even it done. 
like use this ngt.index.create(), it's still not work. show errors .

I just know it's not the NGT error. it's my os version or something else.
And my is Catalina

And I'm quit that. 

And the End, Thank You!
