### ISSUE TITLE
what tool to draw the image

### ISSUE THREAD

**Issue by lilothar** [yahoojapan/NGT#159]
[ngt wiki](https://github.com/yahoojapan/NGT/wiki) I found that, the images in the are wonderful, can you help me known what tools to using to draw it?

**Comment by masajiro** [comment]
Except for [this figure](https://raw.githubusercontent.com/wiki/yahoojapan/NGT/assets/ngt_movie1.gif), I made all the others using PowerPoint. Since [this figure](https://raw.githubusercontent.com/wiki/yahoojapan/NGT/assets/ngt_movie1.gif) was made by my company's professional designer, I don't know which tool was used to make it.

**Comment by lilothar** [comment]
yes, I mean this ones, I am want do something about vector search on dynaimic graph realtime, and wander some way to profile
the graph structure, I found your work are so perfect at most, that I have seen.

**Comment by lilothar** [comment]
and thanks for you replay
