### ISSUE TITLE
Question on dataset characteristics

### ISSUE THREAD

**Issue by kclarke1222** [yahoojapan/NGT#20]
I was curios if these algorithms would work with binary data? I didn't see anything about that in the the papers on the algorithms.

**Comment by masajiro** [comment]
NGT works for binary data with hamming distance as well, although I did not evaluate for hamming distance. When you use hamming distance for binary data, you have to specify 1 byte unsigned integer for the object type and hamming distance for the distance function with NGT [create](https://github.com/yahoojapan/NGT/tree/master/bin/ngt#create) command. Also you should probably make the [search range coefficient](https://github.com/yahoojapan/NGT/tree/master/bin/ngt#search) larger than its default for hamming distance.

**Comment by kclarke1222** [comment]
how about for the jaccard distance? We are operating on binary data, and it is the more typical distance measure in chemistry applications.

**Comment by masajiro** [comment]
Although I have not used the jaccard distance, I think that NGT can work for the jaccard distance as well. But, if the dimensionality of your data is large, NGT cannot effectively handle your data, because NGT cannot handle sparse data.  Anyway since the distance is not implemented at this point, you have to implement it, if you want it in a hurry.

**Comment by masajiro** [comment]
I added jaccard distance.
