### ISSUE TITLE
Question: Is incremental addition and deletion supported?

### ISSUE THREAD

**Issue by stuz5000** [yahoojapan/NGT#38]
Sometimes, its helpful to be able to incrementally add (and sometime delete) to a NN map. Is this supported?

**Comment by masajiro** [comment]
You can remove and add objects.

Append:
https://github.com/yahoojapan/NGT/tree/master/bin/ngt#append
https://github.com/yahoojapan/NGT/blob/master/python/README-ngtpy.md#insert

Remove:
https://github.com/yahoojapan/NGT/tree/master/bin/ngt#remove
https://github.com/yahoojapan/NGT/blob/master/python/README-ngtpy.md#remove

**Comment by saicomagic** [comment]
What's the difference between append and insert? 
https://github.com/yahoojapan/NGT/wiki/Cpp-Quick-Reference#size_t-appendstdvectortype-object
https://github.com/yahoojapan/NGT/wiki/Cpp-Quick-Reference#size_t-insertstdvectortype-object

If the index is constructed with read only mode, is it able to incrementally add or remove?

Many thanks

**Comment by masajiro** [comment]
NGT has an object list to manage objects. append() always adds the given object at the end of the list. The retuned object ID always increases by one for each appending. If the list has no empty entries for removed objects, insert() is the same as append(). However, if the list has empty entries for removed objects, insert() inserts the given object into the empty entry to save the memory space. Note that the ID of the given object must be discontinuous, because the empty entry ID is assigned to the given object.

You cannot construct the index with read only mode.

**Comment by saicomagic** [comment]
> NGT has an object list to manage objects. append() always adds the given object at the end of the list. The retuned object ID always increases by one for each appending. If the list has no empty entries for removed objects, insert() is the same as append(). However, if the list has empty entries for removed objects, insert() inserts the given object into the empty entry to save the memory space. Note that the ID of the given object must be discontinuous, because the empty entry ID is assigned to the given object.
> 
> You cannot construct the index with read only mode.

 Get it! Thanks for your prompt reply.
