### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [yahoojapan/NGT#40]
Hi, thanks for this awesome library 🎉 Just wanted to let you know there are now [Ruby bindings](https://github.com/ankane/ngt) for NGT (thanks to the C API).

I was hoping to support ONNG and wondering if there's a way to call `reconstruct-graph` with the C API. It looks like Python has support with pybind11 and `Optimizer` class. If not, what are your thoughts on adding it to the C API?

I also submitted a pull request to Homebrew to make installation even faster/easier on Mac: https://github.com/Homebrew/homebrew-core/pull/45704

**Comment by masajiro** [comment]
Thank you for your awesome work!

Do you mind if I add the link of your Ruby bindings to NGT [Supported Programming Languages](https://github.com/yahoojapan/NGT/blob/master/README.md#supported-programming-languages)?

Since there are no C APIs to construct ONNG at this time, I will add the C APIs in the near future.

**Comment by ankane** [comment]
Awesome, thanks! Feel free to add a link.

**Comment by ankane** [comment]
The Homebrew formula was just accepted, so users can now do:

```sh
brew install ngt
```

Homebrew precompiles formula, so installation is pretty much instant.

**Comment by masajiro** [comment]
Thank you for letting us know!

**Comment by masajiro** [comment]
I have added some functions for the Optimizer to the C APIs.
https://github.com/yahoojapan/NGT/blob/master/lib/NGT/Capi.h#L140-L151
Since there are no documents about that at this moment, please refer the python bindings below.
https://github.com/yahoojapan/NGT/blob/master/python/src/ngtpy.cpp#L362-L388
If you have any questions, feel free to ask.

**Comment by ankane** [comment]
Awesome, thanks @masajiro. I've installed 1.8.0, but am running into an error when trying to attach two of the functions. I think it's due to inconsistent signatures.

- `ngt_create_optimizer` - header has one argument but cpp file has two
- `ngt_optimizer_set` - header has 12 arguments, cpp file has 11

**Comment by ankane** [comment]
Also, the new version creates an empty `log` file whenever `ngt_create_index` is called. Is there a way to disable this with the C API?

**Comment by masajiro** [comment]
Thank you for letting me know! I fixed the bugs.

**Comment by ankane** [comment]
Thanks, working great now! Added support to Ruby. https://github.com/ankane/ngt/commit/e827cfe4d2f6a6a54d3a380ffc4c22ed2db9553a
