### ISSUE TITLE
performance deterioration using different datasets

### ISSUE THREAD

**Issue by zhaojinzhou** [yahoojapan/NGT#56]
We've met some bad cases. 

search top 120 minimun (1-cos(x,y)) in a dataset of size **100,000** which is  **33 dimensions float** **costs 840ms**.   CPU xeon e5 

when creating index, some warnings occur: `LeafNode::splitObjects: Too many same distances. Reduce internal children size for the tree index or not use the tree index.`

**Comment by masajiro** [comment]
I am interested in the dataset. If possible, could you attach the index here or send it to me to analyze?

**Comment by zhaojinzhou** [comment]
> I am interested in the dataset. If possible, could you attach the index here or send it to me to analyze?

[the dataset](https://raw.githubusercontent.com/zhaojinzhou/json_to_xmind/master/100000_index_tmp.tsv)

My mistake,  840ms is the search time in a  dataset of size 1000,000. 
It takes 40-60ms, when we reduce the size to 100,000.
Not satisfying, as well.

[the query](https://raw.githubusercontent.com/zhaojinzhou/json_to_xmind/master/query.tsv)
[the index zip file](https://raw.githubusercontent.com/zhaojinzhou/json_to_xmind/master/100000_cos.anng.zip)

**Comment by masajiro** [comment]
Thank you for your quick reply.

**Comment by masajiro** [comment]
The parameter setting for your index is below.

`
ngt create -d 33 -o f -D c -E 2 -S 100 100000_cos.anng
`

'-S 100' is too large for most of the datasets. From 5 to 10 looks good for your dataset. Instead of '-S' for index build, '-E' can be used for the search command as follows. These are the same parameter.

`
ngt search -e 0.1 -E 5 100000_cos.anng
`

'0.1' of '-e 0.1' is the default value of '-e' (epsilon). You may want to adjust the value to reduce the search time but also reduce the accuracy in some cases.

Ngtpy has also the same parameters.

**Comment by zhaojinzhou** [comment]
> The parameter setting for your index is below.
> 
> `ngt create -d 33 -o f -D c -E 2 -S 100 100000_cos.anng`
> 
> '-S 100' is too large for most of the datasets. From 5 to 10 looks good for your dataset. Instead of '-S' for index build, '-E' can be used for the search command as follows. These are the same parameter.
> 
> `ngt search -e 0.1 -E 5 100000_cos.anng`
> 
> '0.1' of '-e 0.1' is the default value of '-e' (epsilon). You may want to adjust the value to reduce the search time but also reduce the accuracy in some cases.
> 
> Ngtpy has also the same parameters.

Well, before this , I try a lot of different parameters.   Mainly focused on " -S 100" and " -e 0.1-0.3". It turns out the "-E " parameter, has a great influence on the cost time of query.

Thank you  so much for your help.

Really a great job.

**Comment by mrjj** [comment]
I want to confirm, mainly look up epsilon is contributing to overall search time. We are currently testing NGT on 10-100m scale (~4000dim). And NGT doing awesome, -e is tuned dynamically, so, e.g. when user is reporting non relevant rank system will try not only extend look up limit, but also use larger -e.

The are another less trivial factor as how geometrially close your lookup vector to any centroids, out of major distributions. So, when you e.g. will take vector lying on orthogonal basis e.g. 0.0, 0.0, 1.0, 0.0 and apply cosine distance you may expect query time to grow dramatically, so, NGT are (quite reasonably) is expection that lookup vector will be close to something that is indexed. We have parallel analytical index and scenario of building (quasi) orthogonal decompositions of index space is common scenario that working very slow being compared to more common scenarious.

In some cases just building index with query vectors and then mixing in its centoids to NGT may mitigate this effect. 
Maybe there are more reasons for this, but i've seen same effect on AKNN systems having close design but completely different implementation.

This is not only case when you may meet unexpected query execution time and as far as your index grow, it make sense to handle and peserve all long running queries, otherwise you may get good median execution time but infrastructure being paralyzed by execution of long running queies. Together with this, it might be seen as exploit for your infrastrcture by trivial bayes or other kind of probing search for input symbols that are producing this kind of outlier vectors. 
This is not straightforward moment different from maintainence of traditional tree/inverse indexes.
