### ISSUE TITLE
Size of a disk-mapped index

### ISSUE THREAD

**Issue by usamahjundia** [yahoojapan/NGT#74]
Hi. First of all, thanks for the hard work! I have been looking for an ANN library that supports incremental index addition after building alongside support for mmaped index so i wont need to load everything to memory if it got too big. I almost settled with annoy and just rebuild periodically and then i came accross this library, which pretty much suits my use case!

Question is, i noticed that, the index saved on disk maintains a certain size (i tried using 100, 1000, 10000 sample data, size stays pretty much the same) and i want to know, is this certain size the max expected amount of data im able to store, or will it grow?

Another question is, when appending to an existing index, is there a difference between .insert all the additions and then build and save vs using .batch_insert? i needed the returned ID so i went for the former, and i dont really notice a difference between both

**Comment by masajiro** [comment]
Hi.
> is this certain size the max expected amount of data im able to store, or will it grow?

The size of the stored index grows when you insert more objects than you inserted. The initial index is just one block for the mapped memory file. However, the block size limits the number of inserted objects, because the block size means the maximum size of allocated consecutive memory (It might be a little confusing). By the default, you can insert around 50 million objects. If you would like to insert more, you have to specify the number of inserted objects with "-N" for the NGT command line tool to adjust the size of the block. At this moment, there is no parameter for APIs to change it.

> is there a difference between .insert all the additions and then build and save vs using .batch_insert?

There are two steps for the insertion. First, objects are just inserted into the object repository. Second, the objects are inserted into the indexes apart from the object repository. Since insert() is just the first, you have to call build_index() for the second after multiple insert(). The build_index() is internally parallelized for inserted multiple objects in the object repository to accelerate the processing. The batch_insert() processes the both.

**Comment by usamahjundia** [comment]
Thanks for the answer! Am i correct to say batch_insert is a convenience method, and can i get away with just calling .insert on new vectors and .build_index afterwards to update / add vectors to an index? (i really needed the returned ID and i noticed inserting and building on a prebuilt index took way less than building from scratch, probably meaning .build_index only uses the freshly inserted vectors?

**Comment by masajiro** [comment]
That is right. You do not need to use batch_insert() for your case. After you call insert() and build_index() to build an initial index, you can call insert() and build_index() again to insert additional objects into the initial (prebuilt) index. The second build_index() works not for all, but just for the added objects to insert into the initial index.

**Comment by usamahjundia** [comment]
Thank you! it is all clear now. Thanks for your time and hard work!

Cheers.
