### ISSUE TITLE
Similarity Search not returning acceptable results

### ISSUE THREAD

**Issue by zubair-ahmed-ai** [yahoojapan/NGT#88]
Hi @masajiro 
I am giving this image as a query using the code given [here](https://github.com/yahoojapan/NGT/issues/85) but I am unable to get the desired similarity results, meaning [FAISS](https://github.com/facebookresearch/faiss) was performing better than this on the same images.

This is the query image
![56_1599012000000_1599015600000003_101220](https://user-images.githubusercontent.com/66907171/99931095-2760a200-2d75-11eb-91bb-fb8dae6d63ee.jpg)

And these are the results returned which are no where near perfect matches (except some)
Can you please share what to do @masajiro ?
![56_1599040800000_1599044400000002_315260](https://user-images.githubusercontent.com/66907171/99931195-760e3c00-2d75-11eb-87ad-89742f96e401.jpg)

![56_1599030000000_1599033600000002_399020](https://user-images.githubusercontent.com/66907171/99931193-73abe200-2d75-11eb-8d30-b3bd7c47bfad.jpg)

![56_1599019200000_1599022800000002_490940](https://user-images.githubusercontent.com/66907171/99931149-4eb76f00-2d75-11eb-9ea6-4f7df1c09a0d.jpg)
![56_1599022800000_1599026400000000_537960](https://user-images.githubusercontent.com/66907171/99931157-55de7d00-2d75-11eb-85b1-237e666cbdbc.jpg)

![56_1599019200000_1599022800000002_489760](https://user-images.githubusercontent.com/66907171/99931144-4c551500-2d75-11eb-8c3b-4fd733847418.jpg)

![56_1599012000000_1599015600000003_101460](https://user-images.githubusercontent.com/66907171/99931135-43fcda00-2d75-11eb-9c99-8ed1520244c2.jpg)
ges.githubusercontent.com/66907171/99931132-42331680-2d75-11eb-9c20-e85fc0cfce8d.jpg)share 
![Uploading 56_1599012000000_1599015600000003_101400.jpg…]

![56_1599048000000_1599051600000_1_710820](https://user-images.githubusercontent.com/66907171/99931117-39424500-2d75-11eb-9289-74d1287069a6.jpg)
![56_1599012000000_1599015600000003_101220](https://user-images.githubusercontent.com/66907171/99931128-40695300-2d75-11eb-8590-2db4e576f0d9.jpg)

**Comment by masajiro** [comment]
Hi. If you set higher epsilons for search() like the end of [the section](https://github.com/yahoojapan/NGT/wiki/Practical-Examples-Using-Python#anng-construction-and-search), you can get more accurate results. If you would like exact results, you may want to use [linear_search()](https://github.com/yahoojapan/NGT/blob/master/python/src/ngtpy.cpp#L400) instead of search().

For the difference from faiss's results, please check if you use the same distance as faiss. NGT's default distance function is [L2(Euclidean)](https://github.com/yahoojapan/NGT/blob/master/python/README-ngtpy.md#create). To compare both of them exactly, you may want to compare with distance values as the results. If you use the same distance functions and faiss produces exact distances, the distances of any pair of images are always the same between NGT and faiss.

**Comment by zubair-ahmed-ai** [comment]
@masajiro I tried your suggestions, none of these improve the results. As for comparison of NGT and FAISS, it was more of a visual comparison than checking the distance metrics and such.

Let me know what to do now?

**Comment by zubair-ahmed-ai** [comment]
I tried an epsilon = 2 in the search() method but no improvement

**Comment by masajiro** [comment]
Could you show your resultant rankings with object IDs and distances for the same query using search(), linear_search() and faiss? I will check them.
